export const MOCK_PRODUCTS = [
  {
    id: "bridal-full-hand-set",
    title: "Bridal Full Hand Set",
    slug: "bridal-full-hand-set",
    price: 1499,
    compareAtPrice: 1999,
    style: "Arabic",
    category: "Bridal",
    status: "Best Seller",
    isFeatured: true,
    description: "Our signature full-hand bridal stencil set featuring intricate Malabar-Arabic fusion patterns. Includes 6 individual stencil sheets for both hands — wrist to fingertip coverage. Designed for single-use application pristine hygienic quality.",
    tags: ["bridal", "full-hand", "arabic", "bestseller"],
    image: "https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1542171120-745a907fe23f?auto=format&fit=crop&q=80&w=600",
    ],
  },
  {
    id: "geometric-minimalist-strip",
    title: "Geometric Minimalist Strip",
    slug: "geometric-minimalist-strip",
    price: 349,
    compareAtPrice: null,
    style: "Geometric",
    category: "Everyday",
    status: "New",
    isFeatured: true,
    description: "Clean lines, sharp angles — the anti-traditional stencil for modern minimalists. Single strip fits wrist to mid-forearm. Perfect for festivals and casual wear.",
    tags: ["geometric", "minimalist", "everyday", "new"],
    image: "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=600",
    ],
  },
  {
    id: "classic-arabic-floral",
    title: "Classic Arabic Floral",
    slug: "classic-arabic-floral",
    price: 499,
    compareAtPrice: 699,
    style: "Arabic",
    category: "Festival",
    status: "In Stock",
    isFeatured: true,
    description: "Timeless floral motifs inspired by Arabian court artistry. Full back-hand coverage with delicate finger extensions. A showstopper at any celebration.",
    tags: ["arabic", "floral", "festival"],
    image: "https://images.unsplash.com/photo-1628581691234-807d9f7831f2?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1628581691234-807d9f7831f2?auto=format&fit=crop&q=80&w=600",
    ],
  },
  {
    id: "paisley-precision",
    title: "Paisley Precision",
    slug: "paisley-precision",
    price: 549,
    compareAtPrice: null,
    style: "Paisley",
    category: "Festival",
    status: "Low Stock",
    isFeatured: false,
    description: "Flowing paisleys meet mathematical precision. Each curve is laser-cut for flawless stain transfer. Includes palm and back-hand stencils.",
    tags: ["paisley", "precision", "festival"],
    image: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&q=80&w=600",
    ],
  },
  {
    id: "festival-mandala",
    title: "Festival Mandala",
    slug: "festival-mandala",
    price: 899,
    compareAtPrice: 1199,
    style: "Floral",
    category: "Festival",
    status: "In Stock",
    isFeatured: true,
    description: "Concentric mandala design radiating from the palm center. A spiritual classic reimagined with surgical precision. Our most intricate single-piece stencil.",
    tags: ["mandala", "festival", "intricate"],
    image: "https://images.unsplash.com/photo-1609234656388-0ff363383899?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1609234656388-0ff363383899?auto=format&fit=crop&q=80&w=600",
    ],
  },
  {
    id: "minimalist-lines",
    title: "Minimalist Lines",
    slug: "minimalist-lines",
    price: 299,
    compareAtPrice: null,
    style: "Geometric",
    category: "Everyday",
    status: "New",
    isFeatured: false,
    description: "Parallel lines and negative space. The most effortless way to wear henna. Apply in under 5 minutes for an understated, architectural look.",
    tags: ["minimalist", "geometric", "quick"],
    image: "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=600",
    ],
  },
  {
    id: "royal-rajasthani",
    title: "Royal Rajasthani",
    slug: "royal-rajasthani",
    price: 1299,
    compareAtPrice: 1699,
    style: "Floral",
    category: "Bridal",
    status: "In Stock",
    isFeatured: false,
    description: "Opulent Rajasthani marwari patterns with peacock and lotus motifs. Full arm coverage from wrist to elbow. For brides who demand nothing less than royalty.",
    tags: ["rajasthani", "bridal", "luxury"],
    image: "https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?auto=format&fit=crop&q=80&w=600",
    ],
  },
  {
    id: "finger-tips-collection",
    title: "Finger Tips Collection",
    slug: "finger-tips-collection",
    price: 199,
    compareAtPrice: null,
    style: "Arabic",
    category: "Everyday",
    status: "In Stock",
    isFeatured: false,
    description: "10 individual fingertip stencils — mix and match for a unique look every time. Perfect starter set for henna beginners.",
    tags: ["fingertips", "beginner", "everyday"],
    image: "https://images.unsplash.com/photo-1628581691234-807d9f7831f2?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1628581691234-807d9f7831f2?auto=format&fit=crop&q=80&w=600",
    ],
  },
  {
    id: "eid-special-crescent",
    title: "Eid Special Crescent",
    slug: "eid-special-crescent",
    price: 649,
    compareAtPrice: 849,
    style: "Arabic",
    category: "Festival",
    status: "In Stock",
    isFeatured: true,
    description: "Crescent moon and star motifs woven into flowing arabesques. Designed specifically for Eid celebrations. Back-hand and wrist coverage.",
    tags: ["eid", "crescent", "arabic", "festival"],
    image: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&q=80&w=600",
    ],
  },
  {
    id: "premium-trial-kit",
    title: "Premium Trial Kit",
    slug: "premium-trial-kit",
    price: 399,
    compareAtPrice: 599,
    style: "Floral",
    category: "Everyday",
    status: "Best Seller",
    isFeatured: true,
    description: "3 bestselling stencils in one box — Arabic Floral, Geometric Strip, and Finger Tips. The perfect introduction to Rangrez quality.",
    tags: ["trial", "kit", "bestseller", "gift"],
    image: "https://images.unsplash.com/photo-1609234656388-0ff363383899?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1609234656388-0ff363383899?auto=format&fit=crop&q=80&w=600",
    ],
  },
];

export const COLLECTIONS = [
  {
    id: "bridal",
    title: "Bridal Exclusives",
    slug: "bridal",
    description: "For the most important day. Intricate, full-coverage stencils that rival freehand mastery.",
    image: "https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "festival",
    title: "Festival Collection",
    slug: "festival",
    description: "Eid, Diwali, weddings — celebrate every occasion with precision artistry.",
    image: "https://images.unsplash.com/photo-1609234656388-0ff363383899?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "everyday",
    title: "Everyday Essentials",
    slug: "everyday",
    description: "Quick, minimal, effortless. Henna for the modern lifestyle.",
    image: "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=800",
  },
];

export const INSTAGRAM_REELS = [
  "https://www.instagram.com/girlsforgirls.calicut/reel/DVxTllNEcNA/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DVdLbMdEW_o/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DVNO1WqkVVc/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DT7bZHQEV_B/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DT4R4_IkVxE/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DTnDUY_EaRS/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DTiECDRkdO2/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DTISK1akdpp/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DS9wuXpEd0d/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DS5L7tbEd78/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DSz3r3qkaTr/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DST-ub6EYcd/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DSHTRHGEdX8/",
  "https://www.instagram.com/inaandherliife/reel/DRyiZY4jILv/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DQrmMggE1Ac/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DQeJ2pmkUH0/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DQY0vPIkbg-/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DQLoQFCET-T/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DQGf79aES36/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DP9StNCkQTQ/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DP1BZ0UkYIH/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DPdYOC4kVtL/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DPBGkP1kZRI/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DOc037qEXxK/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DOOUcdsEeZD/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DNe-w8qxLfb/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DNaHmNERcG9/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DNSQ27nR6Yr/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DNCsGM1x_Cr/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DM7NqPixfK3/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DMFQ8iHRC2t/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DL_18YQxkxG/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DL6yeu5RDjx/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DL2Z18uRbQ_/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DLo-wJmxJuL/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DLjzibkxCsS/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DLWkpMGRdxX/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DLE5ZkNxvMA/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DK_d0qlxEGC/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DKuRVniRohr/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DKHDKjRxXXg/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DJrEJRLzzx5/",
  "https://www.instagram.com/ami.ek_/p/DJq0vAjSLH9/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DJl5n0WRz2q/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DJjnGcRzLgJ/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DJUO_U5TNNm/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DJQ_B7yx0_A/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DJGgqmWIpR9/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DJBvziqTjJ-/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DI-lRV0RlMQ/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DI8eP7gxTYR/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DI6YcelTY4q/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DI3BipoxedW/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DI1A-n1zoK0/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DIvVTEmRAbr/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DIoYdQaTTJl/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DIjVvECTdX3/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DIgtkRJRPgp/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DIarrZoxovd/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DITf6lbzFls/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DIRKWuNTRoM/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DIOv5ZRTg99/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DIMZznkzi2E/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DH9ARzQTwgG/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DH5i19CRIGp/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DH5fu8txnr3/",
  "https://www.instagram.com/rangrez_henna_stencils/reel/DH5ejEaRhVO/",
];
